// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRiAKk2puFAoLgZewzo1vPlw2jCF3S0d8',
    appId: '1:729212326917:web:f9c1934f72bb44ec6bb86c',
    messagingSenderId: '729212326917',
    projectId: 'tutorconnect-b900f',
    authDomain: 'tutorconnect-b900f.firebaseapp.com',
    storageBucket: 'tutorconnect-b900f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChzUJC_3tp6ma6kxScecONB3YREpwE76E',
    appId: '1:2181769107:android:c5e6ba84dafa19d9756a66',
    messagingSenderId: '2181769107',
    projectId: 'tutor-29ef9',
    storageBucket: 'tutor-29ef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu7_3ZK0cvk2hcJPCfldD-SzFW6x9qPF4',
    appId: '1:729212326917:ios:2c0b5c6cdff4dc446bb86c',
    messagingSenderId: '729212326917',
    projectId: 'tutorconnect-b900f',
    storageBucket: 'tutorconnect-b900f.appspot.com',
    iosBundleId: 'com.example.tutorConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu7_3ZK0cvk2hcJPCfldD-SzFW6x9qPF4',
    appId: '1:729212326917:ios:2c0b5c6cdff4dc446bb86c',
    messagingSenderId: '729212326917',
    projectId: 'tutorconnect-b900f',
    storageBucket: 'tutorconnect-b900f.appspot.com',
    iosBundleId: 'com.example.tutorConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRiAKk2puFAoLgZewzo1vPlw2jCF3S0d8',
    appId: '1:729212326917:web:e67ece046bd99f0a6bb86c',
    messagingSenderId: '729212326917',
    projectId: 'tutorconnect-b900f',
    authDomain: 'tutorconnect-b900f.firebaseapp.com',
    storageBucket: 'tutorconnect-b900f.appspot.com',
  );
}